### ISSUE TITLE
Low quality of scaled image with canvas: true

### ISSUE THREAD

**Issue by clime** [blueimp/JavaScript-Load-Image#36]
Hey,

with `canvas: true` the quality of scaled images is significantly lower:

![diff](https://f.cloud.github.com/assets/2030528/1455914/c1670704-4321-11e3-9fc4-67ba3a46d636.png)
On the left is the result with `canvas: false`, and on the right is result with `canvas: true`.
This is result from Chrome, in Firefox it looks the same. I haven't tried IE.

This is the original image:

![1](https://f.cloud.github.com/assets/2030528/1455935/0908c80e-4322-11e3-8df2-08e2a3ba496e.jpg)

**Comment by thehappycoder** [comment]
I think it's not a problem anymore. I am not 100% sure though.

**Comment by blueimp** [comment]
Thanks for bringing this up again @thehappycoder.

Modern browsers do image smoothing by default which has better results than the output referenced in the original post here, so I think we can close this.

For reference, the library also supports the following two options since resolving #95:
- [imageSmoothingEnabled](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled)
- [imageSmoothingQuality](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingQuality)
